/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.coffecheap.vista;

/**
 *
 * @author javam
 */
public class frmEstado_mesaEliminar extends javax.swing.JPanel {

    /**
     * Creates new form frmEstado_mesaEliminar
     */
    public frmEstado_mesaEliminar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panPrincipal = new javax.swing.JPanel();
        lblIngreso = new javax.swing.JLabel();
        txtCodigoElimar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        scpPrincipal = new javax.swing.JScrollPane();
        tblEstado_mesaEliminar = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panPrincipal.setLayout(null);

        lblIngreso.setText("Ingrese El Codigo a Eliminar");
        panPrincipal.add(lblIngreso);
        lblIngreso.setBounds(410, 80, 190, 14);

        txtCodigoElimar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panPrincipal.add(txtCodigoElimar);
        txtCodigoElimar.setBounds(380, 110, 210, 30);

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        panPrincipal.add(btnEliminar);
        btnEliminar.setBounds(520, 170, 110, 31);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setText("Estado Mesa");
        panPrincipal.add(lblTitulo);
        lblTitulo.setBounds(400, 30, 160, 29);

        tblEstado_mesaEliminar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpPrincipal.setViewportView(tblEstado_mesaEliminar);

        panPrincipal.add(scpPrincipal);
        scpPrincipal.setBounds(10, 230, 900, 200);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 919;
        gridBagConstraints.ipady = 469;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 3);
        add(panPrincipal, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEliminar;
    private javax.swing.JLabel lblIngreso;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JScrollPane scpPrincipal;
    public javax.swing.JTable tblEstado_mesaEliminar;
    public javax.swing.JTextField txtCodigoElimar;
    // End of variables declaration//GEN-END:variables
}
