/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.coffecheap.vista;

/**
 *
 * @author user
 */
public class frmEstado_mesaModificar extends javax.swing.JPanel {

    /**
     * Creates new form frmEstado_mesaModificar
     */
    public frmEstado_mesaModificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panPrincipal = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblObservaciones = new javax.swing.JLabel();
        txtCodigoMod = new javax.swing.JTextField();
        txtNombreMod = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        scpPrincipal = new javax.swing.JScrollPane();
        tblEstado_mesaModificar = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panPrincipal.setLayout(null);

        lblCodigo.setText("Codigo:");
        panPrincipal.add(lblCodigo);
        lblCodigo.setBounds(290, 100, 80, 14);

        lblObservaciones.setText("Nombre:");
        panPrincipal.add(lblObservaciones);
        lblObservaciones.setBounds(290, 160, 100, 14);

        txtCodigoMod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panPrincipal.add(txtCodigoMod);
        txtCodigoMod.setBounds(410, 90, 230, 40);

        txtNombreMod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panPrincipal.add(txtNombreMod);
        txtNombreMod.setBounds(410, 150, 230, 40);

        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        panPrincipal.add(btnModificar);
        btnModificar.setBounds(520, 210, 120, 40);

        tblEstado_mesaModificar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpPrincipal.setViewportView(tblEstado_mesaModificar);

        panPrincipal.add(scpPrincipal);
        scpPrincipal.setBounds(40, 310, 910, 200);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setText("Estado Mesa");
        panPrincipal.add(lblTitulo);
        lblTitulo.setBounds(420, 20, 149, 29);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 976;
        gridBagConstraints.ipady = 529;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 14, 2);
        add(panPrincipal, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnModificar;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JScrollPane scpPrincipal;
    public javax.swing.JTable tblEstado_mesaModificar;
    public javax.swing.JTextField txtCodigoMod;
    public javax.swing.JTextField txtNombreMod;
    // End of variables declaration//GEN-END:variables
}
