/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.coffecheap.vista;

/**
 *
 * @author javam
 */
public class frmOrden_ComprasGuardar extends javax.swing.JPanel {

    /**
     * Creates new form frmEstado_mesa
     */
    public frmOrden_ComprasGuardar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    panPrincipal = new javax.swing.JPanel();
    lbIDOrdenCompras = new javax.swing.JLabel();
    txtIdOrdenComprasGuardar = new javax.swing.JTextField();
    btnGuardar = new javax.swing.JButton();
    lblFechaOrden = new javax.swing.JLabel();
    txtFechaOrdenGuardar = new javax.swing.JTextField();
    lblFechaEntrega = new javax.swing.JLabel();
    txtFechaEntregaGuardar = new javax.swing.JTextField();
    lblProveedor = new javax.swing.JLabel();
    txtCantidadOrdenGuardar = new javax.swing.JTextField();
    jCProveedor = new javax.swing.JComboBox<>();
    lblCantidadOrden = new javax.swing.JLabel();
    lblProducto = new javax.swing.JLabel();
    jCProducto = new javax.swing.JComboBox<>();

    setBackground(new java.awt.Color(255, 255, 255));
    setPreferredSize(new java.awt.Dimension(1570, 800));
    setLayout(new java.awt.GridBagLayout());

    panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
    panPrincipal.setLayout(null);

    lbIDOrdenCompras.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    lbIDOrdenCompras.setText("id Orden Compras");
    panPrincipal.add(lbIDOrdenCompras);
    lbIDOrdenCompras.setBounds(220, 90, 140, 19);

    txtIdOrdenComprasGuardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    panPrincipal.add(txtIdOrdenComprasGuardar);
    txtIdOrdenComprasGuardar.setBounds(370, 80, 230, 40);

    btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    btnGuardar.setText("Guardar");
    panPrincipal.add(btnGuardar);
    btnGuardar.setBounds(400, 390, 120, 40);

    lblFechaOrden.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    lblFechaOrden.setText("Fecha de Orde");
    panPrincipal.add(lblFechaOrden);
    lblFechaOrden.setBounds(250, 140, 110, 19);

    txtFechaOrdenGuardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    panPrincipal.add(txtFechaOrdenGuardar);
    txtFechaOrdenGuardar.setBounds(370, 130, 230, 40);

    lblFechaEntrega.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    lblFechaEntrega.setText("Fecha de Entrega");
    panPrincipal.add(lblFechaEntrega);
    lblFechaEntrega.setBounds(230, 190, 130, 19);

    txtFechaEntregaGuardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    panPrincipal.add(txtFechaEntregaGuardar);
    txtFechaEntregaGuardar.setBounds(370, 180, 230, 40);

    lblProveedor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    lblProveedor.setText("Proveedor");
    panPrincipal.add(lblProveedor);
    lblProveedor.setBounds(250, 290, 110, 19);

    txtCantidadOrdenGuardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    panPrincipal.add(txtCantidadOrdenGuardar);
    txtCantidadOrdenGuardar.setBounds(370, 230, 230, 40);

    jCProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    panPrincipal.add(jCProveedor);
    jCProveedor.setBounds(370, 290, 230, 26);

    lblCantidadOrden.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    lblCantidadOrden.setText("Cantidad Orden");
    panPrincipal.add(lblCantidadOrden);
    lblCantidadOrden.setBounds(240, 240, 120, 19);

    lblProducto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    lblProducto.setText("Producto");
    panPrincipal.add(lblProducto);
    lblProducto.setBounds(250, 330, 110, 19);

    jCProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    panPrincipal.add(jCProducto);
    jCProducto.setBounds(370, 330, 230, 26);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.ipadx = 909;
    gridBagConstraints.ipady = 459;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    add(panPrincipal, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btnGuardar;
  private javax.swing.JComboBox<String> jCProducto;
  private javax.swing.JComboBox<String> jCProveedor;
  private javax.swing.JLabel lbIDOrdenCompras;
  private javax.swing.JLabel lblCantidadOrden;
  private javax.swing.JLabel lblFechaEntrega;
  private javax.swing.JLabel lblFechaOrden;
  private javax.swing.JLabel lblProducto;
  private javax.swing.JLabel lblProveedor;
  private javax.swing.JPanel panPrincipal;
  public javax.swing.JTextField txtCantidadOrdenGuardar;
  public javax.swing.JTextField txtFechaEntregaGuardar;
  public javax.swing.JTextField txtFechaOrdenGuardar;
  public javax.swing.JTextField txtIdOrdenComprasGuardar;
  // End of variables declaration//GEN-END:variables
}
