/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.coffecheap.vista;

/**
 *
 * @author user
 */
public class frmOrden_ComprasModificar extends javax.swing.JPanel {

    /**
     * Creates new form frmEstado_mesaModificar
     */
    public frmOrden_ComprasModificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    panPrincipal = new javax.swing.JPanel();
    btnModificar = new javax.swing.JButton();
    scpPrincipal = new javax.swing.JScrollPane();
    tblOrden_ComprasModificar = new javax.swing.JTable();
    lblTitulo = new javax.swing.JLabel();
    lbIDOrdenCompras = new javax.swing.JLabel();
    lblFechaOrden = new javax.swing.JLabel();
    lblFechaEntrega = new javax.swing.JLabel();
    lblCantidadOrden = new javax.swing.JLabel();
    lblProveedor = new javax.swing.JLabel();
    lblProducto = new javax.swing.JLabel();
    txtIdOrdenComprasGuardar = new javax.swing.JTextField();
    txtFechaOrdenGuardar = new javax.swing.JTextField();
    txtFechaEntregaGuardar = new javax.swing.JTextField();
    txtCantidadOrdenGuardar = new javax.swing.JTextField();
    jCProveedor = new javax.swing.JComboBox<>();
    jCProducto = new javax.swing.JComboBox<>();

    setBackground(new java.awt.Color(255, 255, 255));
    setLayout(new java.awt.GridBagLayout());

    panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
    panPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    btnModificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    btnModificar.setText("Modificar");
    panPrincipal.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 120, 40));

    tblOrden_ComprasModificar.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    scpPrincipal.setViewportView(tblOrden_ComprasModificar);

    panPrincipal.add(scpPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 910, 200));

    lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    lblTitulo.setText("Orden Compras");
    panPrincipal.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

    lbIDOrdenCompras.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    lbIDOrdenCompras.setText("id Orden Compras");
    panPrincipal.add(lbIDOrdenCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

    lblFechaOrden.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    lblFechaOrden.setText("Fecha de Orde");
    panPrincipal.add(lblFechaOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

    lblFechaEntrega.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    lblFechaEntrega.setText("Fecha de Entrega");
    panPrincipal.add(lblFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

    lblCantidadOrden.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    lblCantidadOrden.setText("Cantidad Orden");
    panPrincipal.add(lblCantidadOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

    lblProveedor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    lblProveedor.setText("Proveedor");
    panPrincipal.add(lblProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

    lblProducto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    lblProducto.setText("Producto");
    panPrincipal.add(lblProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

    txtIdOrdenComprasGuardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    panPrincipal.add(txtIdOrdenComprasGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 210, -1));

    txtFechaOrdenGuardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    panPrincipal.add(txtFechaOrdenGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 210, -1));

    txtFechaEntregaGuardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    panPrincipal.add(txtFechaEntregaGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 210, -1));

    txtCantidadOrdenGuardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    panPrincipal.add(txtCantidadOrdenGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 210, -1));

    jCProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    panPrincipal.add(jCProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 210, 30));

    jCProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    panPrincipal.add(jCProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 210, 30));

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.ipadx = 27;
    gridBagConstraints.ipady = 99;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 11, 0);
    add(panPrincipal, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btnModificar;
  private javax.swing.JComboBox<String> jCProducto;
  private javax.swing.JComboBox<String> jCProveedor;
  private javax.swing.JLabel lbIDOrdenCompras;
  private javax.swing.JLabel lblCantidadOrden;
  private javax.swing.JLabel lblFechaEntrega;
  private javax.swing.JLabel lblFechaOrden;
  private javax.swing.JLabel lblProducto;
  private javax.swing.JLabel lblProveedor;
  private javax.swing.JLabel lblTitulo;
  private javax.swing.JPanel panPrincipal;
  private javax.swing.JScrollPane scpPrincipal;
  public javax.swing.JTable tblOrden_ComprasModificar;
  public javax.swing.JTextField txtCantidadOrdenGuardar;
  public javax.swing.JTextField txtFechaEntregaGuardar;
  public javax.swing.JTextField txtFechaOrdenGuardar;
  public javax.swing.JTextField txtIdOrdenComprasGuardar;
  // End of variables declaration//GEN-END:variables
}
