/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.coffecheap.vista;

/**
 *
 * @author user
 */
public class frmPlatoGuardar extends javax.swing.JPanel {

    /**
     * Creates new form frmTurnoModificar
     */
    public frmPlatoGuardar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        lblId_Plato = new javax.swing.JLabel();
        lblNombre_Platillo = new javax.swing.JLabel();
        txtNombrePlatillo = new javax.swing.JTextField();
        txtTipoPlato = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblPrecio_Plato = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lblPorciones = new javax.swing.JLabel();
        txtPorciones = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        lblId_Plato.setText("Tipo Plato:");
        lblId_Plato.setToolTipText("");

        lblNombre_Platillo.setText("Nombre Platillo:");
        lblNombre_Platillo.setToolTipText("");

        txtNombrePlatillo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombrePlatillo.setAutoscrolls(false);
        txtNombrePlatillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePlatilloActionPerformed(evt);
            }
        });
        txtNombrePlatillo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombrePlatilloKeyTyped(evt);
            }
        });

        txtTipoPlato.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTipoPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoPlatoActionPerformed(evt);
            }
        });
        txtTipoPlato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTipoPlatoKeyTyped(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");

        lblPrecio_Plato.setText("Precio Plato");

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        lblPorciones.setText("Porciones:");

        txtPorciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPorcionesActionPerformed(evt);
            }
        });
        txtPorciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPorcionesKeyTyped(evt);
            }
        });

        lblDescripcion.setText("Descripcion del Plato");

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDescripcion)
                                    .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNombre_Platillo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblId_Plato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(lblPrecio_Plato)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addComponent(txtNombrePlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(lblPorciones)
                                .addGap(18, 18, 18)
                                .addComponent(txtPorciones, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(199, 199, 199))
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPorciones)
                    .addComponent(lblNombre_Platillo)
                    .addComponent(txtNombrePlatillo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtPorciones))
                .addGap(18, 18, 18)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrecio_Plato)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTipoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId_Plato))
                .addGap(16, 16, 16)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(panPrincipal, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombrePlatilloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombrePlatilloKeyTyped

    }//GEN-LAST:event_txtNombrePlatilloKeyTyped

    private void txtTipoPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoPlatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoPlatoActionPerformed

    private void txtNombrePlatilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePlatilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePlatilloActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtPorcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorcionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPorcionesActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtTipoPlatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipoPlatoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
    }              
    }//GEN-LAST:event_txtTipoPlatoKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        // TODO add your handling code here:
                   
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtPorcionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcionesKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
    }              
    }//GEN-LAST:event_txtPorcionesKeyTyped

 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblId_Plato;
    private javax.swing.JLabel lblNombre_Platillo;
    private javax.swing.JLabel lblPorciones;
    private javax.swing.JLabel lblPrecio_Plato;
    private javax.swing.JPanel panPrincipal;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtNombrePlatillo;
    public javax.swing.JTextField txtPorciones;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txtTipoPlato;
    // End of variables declaration//GEN-END:variables
}
