/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.coffecheap.vista;

/**
 *
 * @author user
 */
public class frmProveedorGuardar extends javax.swing.JPanel {

    /**
     * Creates new form frmProveedorGuardar
     */
    public frmProveedorGuardar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNit = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(267, 444, 34, 14);

        txtNombre.setText("jTextField1");
        jPanel1.add(txtNombre);
        txtNombre.setBounds(366, 438, 59, 20);

        txtNit.setText("jTextField2");
        jPanel1.add(txtNit);
        txtNit.setBounds(366, 484, 59, 20);

        txtTelefono.setText("jTextField3");
        jPanel1.add(txtTelefono);
        txtTelefono.setBounds(366, 522, 59, 20);

        txtEmail.setText("jTextField4");
        jPanel1.add(txtEmail);
        txtEmail.setBounds(366, 560, 59, 20);

        txtDireccion.setText("jTextField5");
        jPanel1.add(txtDireccion);
        txtDireccion.setBounds(366, 598, 59, 20);

        jTextField6.setText("jTextField6");
        jPanel1.add(jTextField6);
        jTextField6.setBounds(366, 636, 59, 20);

        jLabel2.setBackground(new java.awt.Color(204, 255, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/coffecheap/imagenes/about.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 60, 310, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
