/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.coffecheap.vista;

/**
 *
 * @author user
 */
public class frmTipoTransaccionModificar extends javax.swing.JPanel {

    /**
     * Creates new form frmTurnoModificar
     */
    public frmTipoTransaccionModificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panPrincipal = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblObservaciones = new javax.swing.JLabel();
        txtCodigoMod = new javax.swing.JTextField();
        txtnombretipo = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        scpPrincipal = new javax.swing.JScrollPane();
        tblTurnoModificar = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panPrincipal.setLayout(null);

        lblCodigo.setText("Id Tipo:");
        panPrincipal.add(lblCodigo);
        lblCodigo.setBounds(290, 40, 80, 14);

        lblObservaciones.setText("Nombre Tipo:");
        panPrincipal.add(lblObservaciones);
        lblObservaciones.setBounds(280, 110, 100, 14);

        txtCodigoMod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCodigoMod.setAutoscrolls(false);
        txtCodigoMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoModKeyTyped(evt);
            }
        });
        panPrincipal.add(txtCodigoMod);
        txtCodigoMod.setBounds(410, 30, 230, 40);

        txtnombretipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panPrincipal.add(txtnombretipo);
        txtnombretipo.setBounds(410, 100, 230, 40);

        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        panPrincipal.add(btnModificar);
        btnModificar.setBounds(520, 210, 120, 40);

        tblTurnoModificar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpPrincipal.setViewportView(tblTurnoModificar);

        panPrincipal.add(scpPrincipal);
        scpPrincipal.setBounds(10, 280, 910, 200);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 929;
        gridBagConstraints.ipady = 489;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 24, 23);
        add(panPrincipal, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoModKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoModKeyTyped
        char c = evt.getKeyChar();
        
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoModKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnModificar;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JScrollPane scpPrincipal;
    public javax.swing.JTable tblTurnoModificar;
    public javax.swing.JTextField txtCodigoMod;
    public javax.swing.JTextField txtnombretipo;
    // End of variables declaration//GEN-END:variables
}
