/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.coffecheap.vista;

import com.coffecheap.bean.CambiaPanel;

/**
 *
 * @author javam
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
        panTurno.setVisible(false);
        panProveedor.setVisible(false);
        panCompra.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        panCompra = new javax.swing.JPanel();
        btnGuardarCompra = new javax.swing.JButton();
        btnEliminarCompra = new javax.swing.JButton();
        btnModificarCompra = new javax.swing.JButton();
        panProveedor = new javax.swing.JPanel();
        btnGuardarProveedor = new javax.swing.JButton();
        btnEliminarProveedor = new javax.swing.JButton();
        btnModificarProveedor = new javax.swing.JButton();
        panTurno = new javax.swing.JPanel();
        btnGuardarTurno = new javax.swing.JButton();
        btnEliminarTurno = new javax.swing.JButton();
        btnModificarTurno = new javax.swing.JButton();
        panEncabezado = new javax.swing.JPanel();
        panMenu = new javax.swing.JPanel();
        btnTurno = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnCompra = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnMesa = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        panDatos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panPrincipal.setLayout(null);

        panCompra.setBackground(new java.awt.Color(49, 59, 63));
        panCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panCompra.setLayout(null);

        btnGuardarCompra.setText("Guardar");
        panCompra.add(btnGuardarCompra);
        btnGuardarCompra.setBounds(20, 10, 80, 23);

        btnEliminarCompra.setText("Eliminar");
        panCompra.add(btnEliminarCompra);
        btnEliminarCompra.setBounds(20, 40, 80, 23);

        btnModificarCompra.setText("Modificar");
        panCompra.add(btnModificarCompra);
        btnModificarCompra.setBounds(10, 70, 100, 23);

        panPrincipal.add(panCompra);
        panCompra.setBounds(0, 0, 120, 110);

        panProveedor.setBackground(new java.awt.Color(49, 59, 63));
        panProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panProveedor.setLayout(null);

        btnGuardarProveedor.setText("Guardar");
        panProveedor.add(btnGuardarProveedor);
        btnGuardarProveedor.setBounds(20, 10, 80, 23);

        btnEliminarProveedor.setText("Eliminar");
        panProveedor.add(btnEliminarProveedor);
        btnEliminarProveedor.setBounds(20, 40, 80, 23);

        btnModificarProveedor.setText("Modificar");
        panProveedor.add(btnModificarProveedor);
        btnModificarProveedor.setBounds(10, 70, 100, 23);

        panPrincipal.add(panProveedor);
        panProveedor.setBounds(0, 0, 120, 110);

        panTurno.setBackground(new java.awt.Color(49, 59, 63));
        panTurno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panTurno.setLayout(null);

        btnGuardarTurno.setText("Guardar");
        panTurno.add(btnGuardarTurno);
        btnGuardarTurno.setBounds(20, 10, 80, 23);

        btnEliminarTurno.setText("Eliminar");
        panTurno.add(btnEliminarTurno);
        btnEliminarTurno.setBounds(20, 40, 80, 23);

        btnModificarTurno.setText("Modificar");
        panTurno.add(btnModificarTurno);
        btnModificarTurno.setBounds(10, 70, 100, 23);

        panPrincipal.add(panTurno);
        panTurno.setBounds(0, 0, 120, 110);

        panEncabezado.setBackground(new java.awt.Color(239, 243, 246));
        panEncabezado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panPrincipal.add(panEncabezado);
        panEncabezado.setBounds(250, 0, 1680, 70);

        panMenu.setBackground(new java.awt.Color(92, 102, 106));
        panMenu.setLayout(null);

        btnTurno.setBackground(new java.awt.Color(49, 59, 63));
        btnTurno.setForeground(new java.awt.Color(255, 255, 255));
        btnTurno.setText("Turno");
        btnTurno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panMenu.add(btnTurno);
        btnTurno.setBounds(0, 210, 250, 40);

        btnProveedor.setBackground(new java.awt.Color(49, 59, 63));
        btnProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnProveedor.setText("Proveedor");
        btnProveedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panMenu.add(btnProveedor);
        btnProveedor.setBounds(0, 260, 250, 40);

        btnCompra.setBackground(new java.awt.Color(49, 59, 63));
        btnCompra.setForeground(new java.awt.Color(255, 255, 255));
        btnCompra.setText("Compra");
        btnCompra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panMenu.add(btnCompra);
        btnCompra.setBounds(0, 310, 250, 40);

        btnUsuario.setBackground(new java.awt.Color(49, 59, 63));
        btnUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario.setText("Usuario");
        btnUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panMenu.add(btnUsuario);
        btnUsuario.setBounds(0, 110, 250, 40);

        btnCliente.setBackground(new java.awt.Color(49, 59, 63));
        btnCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCliente.setText("Cliente");
        btnCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panMenu.add(btnCliente);
        btnCliente.setBounds(0, 160, 250, 40);

        btnMesa.setBackground(new java.awt.Color(49, 59, 63));
        btnMesa.setForeground(new java.awt.Color(255, 255, 255));
        btnMesa.setText("Mesa");
        btnMesa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panMenu.add(btnMesa);
        btnMesa.setBounds(0, 360, 250, 40);

        btnProducto.setBackground(new java.awt.Color(49, 59, 63));
        btnProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnProducto.setText("Producto");
        btnProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panMenu.add(btnProducto);
        btnProducto.setBounds(0, 410, 250, 40);

        panPrincipal.add(panMenu);
        panMenu.setBounds(0, 0, 250, 1030);

        panDatos.setBackground(new java.awt.Color(255, 255, 255));
        panDatos.setLayout(new javax.swing.BoxLayout(panDatos, javax.swing.BoxLayout.LINE_AXIS));
        panPrincipal.add(panDatos);
        panDatos.setBounds(250, 70, 1680, 960);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1928, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCliente;
    public javax.swing.JButton btnCompra;
    public javax.swing.JButton btnEliminarCompra;
    public javax.swing.JButton btnEliminarProveedor;
    public javax.swing.JButton btnEliminarTurno;
    public javax.swing.JButton btnGuardarCompra;
    public javax.swing.JButton btnGuardarProveedor;
    public javax.swing.JButton btnGuardarTurno;
    public javax.swing.JButton btnMesa;
    public javax.swing.JButton btnModificarCompra;
    public javax.swing.JButton btnModificarProveedor;
    public javax.swing.JButton btnModificarTurno;
    public javax.swing.JButton btnProducto;
    public javax.swing.JButton btnProveedor;
    public javax.swing.JButton btnTurno;
    public javax.swing.JButton btnUsuario;
    public javax.swing.JPanel panCompra;
    public javax.swing.JPanel panDatos;
    public javax.swing.JPanel panEncabezado;
    public javax.swing.JPanel panMenu;
    public javax.swing.JPanel panPrincipal;
    public javax.swing.JPanel panProveedor;
    public javax.swing.JPanel panTurno;
    // End of variables declaration//GEN-END:variables
}
